pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID     = credentials('aws_access_key_id')
        AWS_SECRET_ACCESS_KEY = credentials('aws_secret_access_key')
        AWS_DEFAULT_REGION    = 'us-east-1'
    }
      stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/AshokTippaluri/Terraform_project.git'
            }
        }
        stage('Terraform init') {
            steps {
                sh 'pwd'
                sh 'cd terraform_ng/ng/'
                sh 'pwd && ls -al'
                sh 'terraform init'
            }
        }
        stage('validate') {
            steps {
                sh 'terraform validate'
                sh 'terraform plan'
            }
        }
      }
}
